version: '3.8'

services:
  mongo:
    image: mongo:8.0
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${ETL_TEMPLATE_MONGO_PASSWORD}
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${ETL_TEMPLATE_POSTGRESQL_PASSWORD}
      POSTGRES_DB: testdb
    volumes:
      - ./src/test/resources/sql:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped

  etl-template-with-flink-jobmanager:
    image: template/etl-template-with-flink
    container_name: etl-template-with-flink-jobmanager
    build:
      context: .
      dockerfile: Dockerfile
    command: jobmanager
    ports:
      - "8081:8081"
    environment:
      JOB_MANAGER_RPC_ADDRESS: etl-template-with-flink-jobmanager
      POSTGRESQL_URL: jdbc:postgresql://postgres:5432/testdb
      POSTGRESQL_USER: admin
      POSTGRESQL_PASSWORD: ${ETL_TEMPLATE_POSTGRESQL_PASSWORD}
      MONGODB_URI: mongodb://admin:${ETL_TEMPLATE_MONGO_PASSWORD}@mongo:27017
      MONGODB_DATABASE: local
    depends_on:
      - mongo
      - postgres
    restart: unless-stopped

  etl-template-with-flink-taskmanager:
    image: template/etl-template-with-flink
    container_name: etl-template-with-flink-taskmanager
    build:
      context: .
      dockerfile: Dockerfile
    command: taskmanager
    environment:
      JOB_MANAGER_RPC_ADDRESS: etl-template-with-flink-jobmanager
      POSTGRESQL_URL: jdbc:postgresql://postgres:5432/testdb
      POSTGRESQL_USER: admin
      POSTGRESQL_PASSWORD: ${ETL_TEMPLATE_POSTGRESQL_PASSWORD}
      MONGODB_URI: mongodb://admin:${ETL_TEMPLATE_POSTGRESQL_PASSWORD}@mongo:27017
      MONGODB_DATABASE: local
    depends_on:
      - etl-template-with-flink-jobmanager
    restart: unless-stopped